USE bd4A3;

CREATE TABLE IF NOT EXISTS tests (
	id int(11) PRIMARY KEY AUTO_INCREMENT,
	prenom varchar(50) DEFAULT NULL,
	nom varchar(50) DEFAULT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL
);