services:
    mariadb:
        container_name: "mariadb"
        image: mariadb:10.11
        ports:
            - "3306:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_DATABASE=bd4A3
        volumes:
            - "./database/init:/docker-entrypoint-initdb.d"
            - "./database/data/mariadb:/var/lib/mysql"
    phpmyadmin:
        container_name: local-phpmyadmin
        image: phpmyadmin:5.2.1
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - PMA_HOST=mariadb
        ports:
        - 8081:80